// Curated JSON data structure of 5-letter STEM words for high school students
// Each word includes its category and 3 progressive hints

export interface StemWord {
  word: string;
  category: string;
  hints: [string, string, string];
}

export const STEM_WORD_DATA: StemWord[] = [
  // ── Biology ──
  { word: "genes", category: "Biology", hints: ["Units of heredity passed from parent to offspring", "Found on chromosomes in the cell nucleus", "Made of DNA sequences that code for proteins"] },
  { word: "cells", category: "Biology", hints: ["The basic structural unit of all living organisms", "Discovered by Robert Hooke in 1665", "Contain organelles like mitochondria and ribosomes"] },
  { word: "flora", category: "Biology", hints: ["The plant life of a particular region", "Often paired with fauna in ecology", "A rainforest has diverse ___"] },
  { word: "fauna", category: "Biology", hints: ["The animal life of a particular region", "Often paired with flora in ecology", "Marine ___ includes fish and whales"] },
  { word: "biome", category: "Biology", hints: ["A large ecological community type", "Examples include tundra, desert, and rainforest", "Defined by climate and dominant vegetation"] },
  { word: "clone", category: "Biology", hints: ["A genetically identical copy", "Dolly the sheep was the first mammal ___", "Produced through asexual reproduction or lab techniques"] },
  { word: "fungi", category: "Biology", hints: ["A kingdom of organisms that includes mushrooms", "They decompose organic matter", "Yeasts and molds belong to this group"] },
  { word: "larva", category: "Biology", hints: ["An immature form of an insect", "A caterpillar is one of these", "Undergoes metamorphosis to become an adult"] },
  { word: "liver", category: "Biology", hints: ["The largest internal organ in the body", "It detoxifies chemicals and metabolizes drugs", "Produces bile for digestion"] },
  { word: "lymph", category: "Biology", hints: ["A fluid in the immune system", "Carried through vessels and nodes", "Helps fight infections and remove waste"] },
  { word: "mucus", category: "Biology", hints: ["A slippery secretion of membranes", "Lines the respiratory and digestive tracts", "Traps dust and pathogens before they enter lungs"] },
  { word: "nerve", category: "Biology", hints: ["Carries electrical signals in the body", "Part of the nervous system", "Bundles of axons wrapped in connective tissue"] },
  { word: "organ", category: "Biology", hints: ["A structure with a specific vital function", "The heart and lungs are examples", "Made of multiple tissue types working together"] },
  { word: "ovary", category: "Biology", hints: ["Produces egg cells in females", "Part of the reproductive system", "In plants, it develops into a fruit after fertilization"] },
  { word: "plant", category: "Biology", hints: ["An organism that photosynthesizes", "Belongs to kingdom Plantae", "Has roots, stems, and leaves"] },
  { word: "serum", category: "Biology", hints: ["The clear liquid part of blood", "Remains after clotting factors are removed", "Used in medical tests and vaccines"] },
  { word: "skull", category: "Biology", hints: ["The bony structure of the head", "Protects the brain", "Made of cranial and facial bones"] },
  { word: "spine", category: "Biology", hints: ["The vertebral column", "Protects the spinal cord", "Humans have 33 vertebrae in this structure"] },
  { word: "spore", category: "Biology", hints: ["A reproductive cell in fungi and plants", "Can survive harsh conditions", "Ferns and mosses reproduce using these"] },
  { word: "sweat", category: "Biology", hints: ["Produced by glands in the skin", "Helps regulate body temperature", "Composed mainly of water and salt"] },
  { word: "trait", category: "Biology", hints: ["A characteristic determined by genes", "Eye color is an example", "Can be dominant or recessive"] },
  { word: "tumor", category: "Biology", hints: ["An abnormal mass of tissue", "Can be benign or malignant", "Results from uncontrolled cell division"] },
  { word: "veins", category: "Biology", hints: ["Blood vessels that return blood to the heart", "Carry deoxygenated blood (except pulmonary)", "Have valves to prevent backflow"] },
  { word: "virus", category: "Biology", hints: ["An infectious agent smaller than bacteria", "Needs a host cell to replicate", "COVID-19 is caused by one"] },
  { word: "yeast", category: "Biology", hints: ["A single-celled fungus", "Used in baking and brewing", "Saccharomyces cerevisiae is a common species"] },
  { word: "blood", category: "Biology", hints: ["A fluid connective tissue", "Carries oxygen and nutrients to cells", "Contains red cells, white cells, and plasma"] },
  { word: "brain", category: "Biology", hints: ["The control center of the nervous system", "Has about 86 billion neurons", "Divided into cerebrum, cerebellum, and brainstem"] },
  { word: "femur", category: "Biology", hints: ["The longest bone in the human body", "Located in the upper leg", "Connects the hip to the knee"] },
  { word: "gland", category: "Biology", hints: ["An organ that produces substances", "Can be endocrine or exocrine", "The thyroid and pituitary are examples"] },
  { word: "heart", category: "Biology", hints: ["A muscular organ that pumps blood", "Has four chambers", "Beats about 100,000 times per day"] },
  { word: "joint", category: "Biology", hints: ["Where two or more bones meet", "The knee and elbow are examples", "Can be hinge, ball-and-socket, or pivot type"] },
  { word: "pulse", category: "Biology", hints: ["The rhythmic expansion of arteries", "Can be felt at the wrist or neck", "Indicates heart rate"] },
  { word: "sinus", category: "Biology", hints: ["An air-filled cavity in the skull", "Lined with mucous membrane", "Infections here cause headaches and congestion"] },
  { word: "tibia", category: "Biology", hints: ["The larger bone of the lower leg", "Also called the shinbone", "Bears most of the body's weight below the knee"] },
  { word: "wound", category: "Biology", hints: ["An injury to body tissue", "Can be open or closed", "The body repairs it through clotting and cell growth"] },
  { word: "petal", category: "Biology", hints: ["A colorful part of a flower", "Attracts pollinators like bees", "Surrounds the reproductive organs of the plant"] },
  { word: "seeds", category: "Biology", hints: ["Contain an embryonic plant", "Produced after fertilization in flowering plants", "Dispersed by wind, water, or animals"] },
  { word: "trunk", category: "Biology", hints: ["The main stem of a tree", "Supports branches and transports nutrients", "Contains rings that indicate age"] },
  { word: "toxin", category: "Biology", hints: ["A poisonous substance produced by organisms", "Bacteria and snakes can produce these", "Can trigger immune responses in the body"] },
  // ── Chemistry ──
  { word: "acids", category: "Chemistry", hints: ["Substances with a pH below 7", "Donate hydrogen ions in solution", "Vinegar and lemon juice contain these"] },
  { word: "alloy", category: "Chemistry", hints: ["A mixture of two or more metals", "Bronze and steel are examples", "Created to improve strength or resistance"] },
  { word: "argon", category: "Chemistry", hints: ["A noble gas on the periodic table", "Makes up about 1% of Earth's atmosphere", "Used in welding and light bulbs"] },
  { word: "atoms", category: "Chemistry", hints: ["The smallest unit of a chemical element", "Made of protons, neutrons, and electrons", "Dalton proposed an early theory about these"] },
  { word: "bonds", category: "Chemistry", hints: ["Connections between atoms in molecules", "Can be ionic, covalent, or metallic", "Involve sharing or transferring electrons"] },
  { word: "boron", category: "Chemistry", hints: ["Element number 5 on the periodic table", "A metalloid used in glass and ceramics", "Its symbol is B"] },
  { word: "decay", category: "Chemistry", hints: ["The breakdown of an unstable atomic nucleus", "Radioactive elements undergo this", "Releases alpha, beta, or gamma radiation"] },
  { word: "ether", category: "Chemistry", hints: ["An organic compound with an oxygen bridge", "Historically used as an anesthetic", "Has the general formula R-O-R'"] },
  { word: "flask", category: "Chemistry", hints: ["A container used in laboratories", "Erlenmeyer and volumetric are common types", "Used for mixing and heating chemicals"] },
  { word: "gases", category: "Chemistry", hints: ["One of the three main states of matter", "Particles move freely and fill containers", "Described by Boyle's and Charles's laws"] },
  { word: "ionic", category: "Chemistry", hints: ["A type of chemical bond", "Formed by transfer of electrons", "Sodium chloride (table salt) has this bonding"] },
  { word: "lipid", category: "Chemistry", hints: ["A class of biological molecules", "Includes fats, oils, and waxes", "Insoluble in water but soluble in organic solvents"] },
  { word: "molar", category: "Chemistry", hints: ["Relating to the mole unit in chemistry", "A ___ solution has 1 mol of solute per liter", "Used to express concentration"] },
  { word: "nylon", category: "Chemistry", hints: ["A synthetic polymer", "Used in clothing and ropes", "First produced by Wallace Carothers at DuPont"] },
  { word: "oxide", category: "Chemistry", hints: ["A compound of oxygen with another element", "Rust is iron ___", "Carbon dioxide is a common one"] },
  { word: "ozone", category: "Chemistry", hints: ["A molecule made of three oxygen atoms (O₃)", "Forms a protective layer in the stratosphere", "At ground level, it's a pollutant"] },
  { word: "phase", category: "Chemistry", hints: ["A distinct state of matter", "Solid, liquid, and gas are the main ones", "Transitions between these require energy"] },
  { word: "polar", category: "Chemistry", hints: ["A molecule with unequal charge distribution", "Water is a ___ molecule", "Creates partial positive and negative ends"] },
  { word: "radon", category: "Chemistry", hints: ["A radioactive noble gas", "Can accumulate in basements", "Element number 86 on the periodic table"] },
  { word: "redox", category: "Chemistry", hints: ["A reaction involving electron transfer", "Short for reduction-oxidation", "Rusting and combustion are examples"] },
  { word: "resin", category: "Chemistry", hints: ["A sticky organic substance", "Can be natural (from trees) or synthetic", "Used in plastics, varnishes, and adhesives"] },
  { word: "salts", category: "Chemistry", hints: ["Ionic compounds from acid-base reactions", "Table salt (NaCl) is the most common", "Formed when a cation bonds with an anion"] },
  { word: "solid", category: "Chemistry", hints: ["A state of matter with fixed shape", "Particles are tightly packed", "Ice is water in this state"] },
  { word: "steam", category: "Chemistry", hints: ["Water in the gas phase", "Formed when water boils at 100°C", "Used to generate electricity in power plants"] },
  { word: "steel", category: "Chemistry", hints: ["An alloy of iron and carbon", "Stronger than pure iron", "Used in construction and manufacturing"] },
  { word: "toxic", category: "Chemistry", hints: ["Poisonous to living organisms", "Lead and mercury are ___ metals", "Indicated by a skull-and-crossbones symbol"] },
  { word: "xenon", category: "Chemistry", hints: ["A noble gas with symbol Xe", "Used in flash lamps and ion propulsion", "Element number 54"] },
  { word: "ester", category: "Chemistry", hints: ["An organic compound from acid-alcohol reactions", "Responsible for many fruity smells", "Formed through a condensation reaction"] },
  { word: "inert", category: "Chemistry", hints: ["Chemically unreactive", "Noble gases are described this way", "Does not easily form bonds with other elements"] },
  { word: "metal", category: "Chemistry", hints: ["An element that conducts heat and electricity", "Most elements on the periodic table are this", "Typically shiny, malleable, and ductile"] },
  { word: "sugar", category: "Chemistry", hints: ["A sweet-tasting carbohydrate", "Glucose and sucrose are types", "Chemical formula C₆H₁₂O₆ for glucose"] },
  { word: "yield", category: "Chemistry", hints: ["The amount of product in a reaction", "Can be theoretical or actual", "Percent ___ compares actual to theoretical"] },
  // ── Physics ──
  { word: "angle", category: "Physics", hints: ["Measured in degrees or radians", "Formed where two lines meet", "Important in optics and projectile motion"] },
  { word: "beams", category: "Physics", hints: ["Directed streams of particles or light", "Lasers produce focused ___", "Also structural elements that resist bending"] },
  { word: "delta", category: "Physics", hints: ["The Greek letter Δ used for change", "Δv means change in velocity", "Common in equations for differences"] },
  { word: "diode", category: "Physics", hints: ["An electronic component allowing one-way current", "Has an anode and a cathode", "LEDs are a light-emitting type"] },
  { word: "field", category: "Physics", hints: ["A region where a force acts", "Can be gravitational, electric, or magnetic", "Represented by lines showing direction and strength"] },
  { word: "focal", category: "Physics", hints: ["Relating to a focus point", "A ___ length describes a lens or mirror", "Where parallel light rays converge"] },
  { word: "force", category: "Physics", hints: ["A push or pull on an object", "Measured in Newtons", "F = ma according to Newton's second law"] },
  { word: "gamma", category: "Physics", hints: ["The highest-energy electromagnetic radiation", "Emitted during radioactive decay", "Can penetrate most materials"] },
  { word: "gauss", category: "Physics", hints: ["A unit of magnetic field strength", "Named after mathematician Carl Friedrich ___", "1 Tesla equals 10,000 of these"] },
  { word: "hertz", category: "Physics", hints: ["The unit of frequency", "One ___ equals one cycle per second", "Named after physicist Heinrich ___"] },
  { word: "joule", category: "Physics", hints: ["The SI unit of energy", "Named after James Prescott ___", "One ___ is one Newton-meter of work"] },
  { word: "laser", category: "Physics", hints: ["A device emitting coherent light", "Stands for Light Amplification by Stimulated Emission of Radiation", "Used in surgery, communication, and barcode scanners"] },
  { word: "light", category: "Physics", hints: ["Electromagnetic radiation visible to the eye", "Travels at about 300,000 km/s in a vacuum", "Exhibits both wave and particle properties"] },
  { word: "meter", category: "Physics", hints: ["The SI base unit of length", "About 3.28 feet", "Defined by the speed of light since 1983"] },
  { word: "noise", category: "Physics", hints: ["Unwanted random signal or disturbance", "Reduces signal quality in electronics", "Measured in decibels for sound"] },
  { word: "orbit", category: "Physics", hints: ["The curved path of an object around another", "Planets follow elliptical ones around the Sun", "Governed by gravitational force"] },
  { word: "power", category: "Physics", hints: ["The rate of doing work or transferring energy", "Measured in watts", "P = W/t or P = IV in circuits"] },
  { word: "prism", category: "Physics", hints: ["A transparent object that refracts light", "Splits white light into a spectrum", "Typically triangular in shape"] },
  { word: "quark", category: "Physics", hints: ["A fundamental particle of matter", "Comes in six flavors: up, down, charm, strange, top, bottom", "Three of these make up a proton or neutron"] },
  { word: "radar", category: "Physics", hints: ["Uses radio waves to detect objects", "Stands for Radio Detection And Ranging", "Used in weather forecasting and aviation"] },
  { word: "ratio", category: "Physics", hints: ["A comparison of two quantities", "Speed is the ___ of distance to time", "Expressed as a fraction or with a colon"] },
  { word: "solar", category: "Physics", hints: ["Relating to the Sun", "___ energy is a renewable power source", "___ panels convert sunlight to electricity"] },
  { word: "sonic", category: "Physics", hints: ["Relating to sound waves", "A ___ boom occurs when breaking the sound barrier", "Ultrasound operates above ___ frequencies"] },
  { word: "tesla", category: "Physics", hints: ["The SI unit of magnetic flux density", "Named after inventor Nikola ___", "Equal to one weber per square meter"] },
  { word: "theta", category: "Physics", hints: ["A Greek letter (θ) used for angles", "Common in trigonometry and physics equations", "Often represents the angle of incidence"] },
  { word: "unity", category: "Physics", hints: ["The number one in mathematical terms", "A ratio of ___ means two things are equal", "Power factor of ___ means maximum efficiency"] },
  { word: "volts", category: "Physics", hints: ["The unit of electric potential difference", "Named after Alessandro Volta", "V = IR according to Ohm's law"] },
  { word: "watts", category: "Physics", hints: ["The unit of power", "Named after James Watt", "One ___ equals one joule per second"] },
  { word: "waves", category: "Physics", hints: ["Disturbances that transfer energy", "Can be transverse or longitudinal", "Sound and light travel as these"] },
  { word: "fluid", category: "Physics", hints: ["A substance that flows and has no fixed shape", "Includes both liquids and gases", "Studied in dynamics and mechanics"] },
  { word: "helix", category: "Physics", hints: ["A three-dimensional spiral shape", "DNA has a double ___ structure", "Charged particles trace this path in magnetic fields"] },
  { word: "lever", category: "Physics", hints: ["A simple machine for amplifying force", "Has a fulcrum, effort, and load", "A seesaw is an everyday example"] },
  { word: "magma", category: "Physics", hints: ["Molten rock beneath Earth's surface", "Becomes lava when it reaches the surface", "Found in the mantle and volcanic chambers"] },
  { word: "optic", category: "Physics", hints: ["Relating to sight or light", "Fiber ___ cables transmit data as light", "The ___ nerve connects the eye to the brain"] },
  { word: "rigid", category: "Physics", hints: ["Not flexible; resistant to deformation", "A ___ body doesn't change shape under force", "Opposite of elastic in mechanics"] },
  { word: "shear", category: "Physics", hints: ["A force that acts parallel to a surface", "___ stress can cause layers to slide", "Scissors apply this type of force"] },
  { word: "speed", category: "Physics", hints: ["The rate of change of position", "A scalar quantity (no direction)", "Measured in meters per second"] },
  { word: "surge", category: "Physics", hints: ["A sudden increase in voltage or current", "Power strips protect against electrical ___", "Can damage electronic equipment"] },
  // ── Math ──
  { word: "axiom", category: "Math", hints: ["A statement accepted as true without proof", "The foundation of mathematical systems", "Euclid's postulates are famous examples"] },
  { word: "cubic", category: "Math", hints: ["Relating to the third power", "A ___ equation has degree 3", "A ___ function has the form ax³ + bx² + cx + d"] },
  { word: "curve", category: "Math", hints: ["A line that is not straight", "Parabolas and circles are examples", "The graph of most functions forms one"] },
  { word: "digit", category: "Math", hints: ["A single numerical symbol (0-9)", "The number 42 has two of these", "Binary uses only the ___s 0 and 1"] },
  { word: "equal", category: "Math", hints: ["Having the same value", "Represented by the = symbol", "Both sides of an equation are ___"] },
  { word: "euler", category: "Math", hints: ["A famous Swiss mathematician", "His constant e ≈ 2.718", "His identity e^(iπ) + 1 = 0 links five constants"] },
  { word: "graph", category: "Math", hints: ["A visual representation of data or functions", "Has x and y axes in coordinate geometry", "Can also mean a network of nodes and edges"] },
  { word: "limit", category: "Math", hints: ["The value a function approaches", "Fundamental concept in calculus", "Written as lim as x approaches a value"] },
  { word: "logic", category: "Math", hints: ["The study of valid reasoning", "Uses AND, OR, NOT operations", "Foundation of mathematical proofs and computer science"] },
  { word: "minus", category: "Math", hints: ["The subtraction operation", "Represented by the − symbol", "A negative number is less than zero, or 'below ___'"] },
  { word: "plane", category: "Math", hints: ["A flat two-dimensional surface", "Extends infinitely in all directions", "The Cartesian ___ has x and y coordinates"] },
  { word: "prime", category: "Math", hints: ["A number divisible only by 1 and itself", "2, 3, 5, 7, 11 are the first five", "The fundamental theorem of arithmetic involves these"] },
  { word: "proof", category: "Math", hints: ["A logical argument establishing truth", "Used to verify theorems", "Can be direct, by contradiction, or by induction"] },
  { word: "range", category: "Math", hints: ["The set of all output values of a function", "Paired with domain in function analysis", "For f(x) = x², this is [0, ∞)"] },
  { word: "roots", category: "Math", hints: ["Values where a function equals zero", "Also called solutions or zeros", "The quadratic formula finds these for ax² + bx + c = 0"] },
  { word: "sigma", category: "Math", hints: ["The Greek letter Σ used for summation", "Also represents standard deviation (σ)", "Σ notation compactly writes long sums"] },
  { word: "slope", category: "Math", hints: ["The steepness of a line", "Calculated as rise over run", "In y = mx + b, m is the ___"] },
  { word: "value", category: "Math", hints: ["A numerical quantity", "Variables hold unknown ___s", "Absolute ___ is always non-negative"] },
  { word: "wedge", category: "Math", hints: ["A simple machine that splits objects", "Triangular in cross-section", "An axe head is an example"] },
  { word: "zeros", category: "Math", hints: ["Points where a function crosses the x-axis", "Also called roots of a polynomial", "A quadratic has at most two real ___"] },
  { word: "chord", category: "Math", hints: ["A line segment between two points on a circle", "The diameter is the longest one", "Different from a tangent, which touches at one point"] },
  { word: "depth", category: "Math", hints: ["The third dimension of a 3D object", "Along with length and width", "Measured from top to bottom or front to back"] },
  { word: "locus", category: "Math", hints: ["The set of all points satisfying a condition", "A circle is the ___ of points equidistant from center", "Used in geometric constructions"] },
  { word: "radii", category: "Math", hints: ["Plural of radius", "Line segments from center to edge of a circle", "All ___ of a circle have equal length"] },
  { word: "solve", category: "Math", hints: ["To find the answer to an equation", "Isolating the variable is a common method", "What you do with math problems"] },
  { word: "union", category: "Math", hints: ["Combining two sets together", "Represented by the ∪ symbol", "A ∪ B contains all elements in A or B"] },
  { word: "width", category: "Math", hints: ["The horizontal measurement of an object", "One of the dimensions in area = length × ___", "How wide something is"] },
  { word: "nodes", category: "Math", hints: ["Points in a graph or network", "Connected by edges", "Also called vertices in graph theory"] },
  // ── Computer Science ──
  { word: "array", category: "Computer Science", hints: ["An ordered collection of elements", "Elements accessed by index", "int[] numbers = {1, 2, 3} in Java"] },
  { word: "ascii", category: "Computer Science", hints: ["A character encoding standard", "Maps characters to numbers 0-127", "The letter 'A' is code 65 in this system"] },
  { word: "bytes", category: "Computer Science", hints: ["Units of digital data (8 bits each)", "A kilobyte is 1,024 of these", "Can represent values 0-255"] },
  { word: "cache", category: "Computer Science", hints: ["Fast temporary storage for data", "Speeds up repeated access", "L1 and L2 are CPU ___ levels"] },
  { word: "class", category: "Computer Science", hints: ["A blueprint for creating objects in OOP", "Contains methods and properties", "Instances of a ___ are called objects"] },
  { word: "cloud", category: "Computer Science", hints: ["Remote servers accessed via the internet", "AWS and Azure provide ___ computing", "Stores data off your local device"] },
  { word: "codes", category: "Computer Science", hints: ["Instructions written in a programming language", "Source ___ is human-readable", "Compiled or interpreted to run on machines"] },
  { word: "cycle", category: "Computer Science", hints: ["One complete iteration of a repeating process", "A CPU clock ___ is one tick of the processor", "A for-loop runs through multiple of these"] },
  { word: "debug", category: "Computer Science", hints: ["The process of finding and fixing errors", "Breakpoints and log statements help with this", "Grace Hopper coined the term from an actual bug"] },
  { word: "email", category: "Computer Science", hints: ["Electronic messages sent over the internet", "Uses SMTP, POP3, or IMAP protocols", "Invented in the early 1970s"] },
  { word: "frame", category: "Computer Science", hints: ["A single image in a video or animation", "Also a data packet in networking", "A stack ___ stores function call data"] },
  { word: "index", category: "Computer Science", hints: ["A numerical position in a data structure", "Usually starts at 0 in most languages", "Databases use these to speed up queries"] },
  { word: "input", category: "Computer Science", hints: ["Data entered into a program", "Keyboard and mouse provide user ___", "Functions receive ___ through parameters"] },
  { word: "linux", category: "Computer Science", hints: ["An open-source operating system kernel", "Created by Linus Torvalds in 1991", "Powers most web servers and Android devices"] },
  { word: "loops", category: "Computer Science", hints: ["Code structures that repeat instructions", "for, while, and do-while are common types", "An infinite one runs forever without a break"] },
  { word: "model", category: "Computer Science", hints: ["A representation of a system or concept", "In MVC, it handles data and business logic", "Machine learning trains a ___ on data"] },
  { word: "mouse", category: "Computer Science", hints: ["A pointing input device", "Invented by Douglas Engelbart in 1964", "Has buttons and a scroll wheel"] },
  { word: "pixel", category: "Computer Science", hints: ["The smallest unit of a digital image", "Short for picture element", "A 1080p screen is 1920 × 1080 of these"] },
  { word: "proxy", category: "Computer Science", hints: ["An intermediary server between client and target", "Can filter, cache, or anonymize requests", "A reverse ___ sits in front of web servers"] },
  { word: "query", category: "Computer Science", hints: ["A request for data from a database", "SELECT * FROM users is a SQL ___", "Can filter, sort, and aggregate results"] },
  { word: "queue", category: "Computer Science", hints: ["A first-in-first-out (FIFO) data structure", "Elements are added at the back, removed from front", "Like a line of people waiting"] },
  { word: "regex", category: "Computer Science", hints: ["A pattern for matching text strings", "Short for regular expression", "/^[a-z]+$/ matches lowercase words"] },
  { word: "route", category: "Computer Science", hints: ["A URL path mapped to a handler", "In networking, the path data takes", "/api/users is an example of an API ___"] },
  { word: "stack", category: "Computer Science", hints: ["A last-in-first-out (LIFO) data structure", "Push adds, pop removes the top element", "The call ___ tracks function execution"] },
  { word: "token", category: "Computer Science", hints: ["A unit of data in parsing or authentication", "JWTs are used for secure web ___s", "A lexer breaks source code into these"] },
  { word: "tuple", category: "Computer Science", hints: ["An ordered, immutable collection of elements", "Common in Python: (1, 'hello', True)", "Like a list but cannot be modified"] },
  { word: "crash", category: "Computer Science", hints: ["When a program terminates unexpectedly", "Often caused by unhandled exceptions", "A blue screen of death is a system ___"] },
  { word: "fetch", category: "Computer Science", hints: ["To retrieve data from a source", "A JavaScript API for making HTTP requests", "Part of the CPU instruction cycle"] },
  { word: "heaps", category: "Computer Science", hints: ["Tree-based data structures", "Used to implement priority queues", "Can be min-___ or max-___"] },
  { word: "image", category: "Computer Science", hints: ["A visual representation stored digitally", "Common formats: PNG, JPEG, GIF", "A Docker ___ is a container template"] },
  { word: "merge", category: "Computer Science", hints: ["Combining two sorted lists into one", "___ sort is an O(n log n) algorithm", "In Git, combining branches is called a ___"] },
  { word: "parse", category: "Computer Science", hints: ["Analyzing a string according to grammar rules", "JSON.___ converts text to a JavaScript object", "Compilers ___ source code into syntax trees"] },
  { word: "print", category: "Computer Science", hints: ["Output text to the console or screen", "___('Hello World') is often the first program", "A debugging technique before using debuggers"] },
  { word: "shell", category: "Computer Science", hints: ["A command-line interface to the OS", "Bash and Zsh are common Unix ___s", "Interprets user commands and runs programs"] },
  { word: "table", category: "Computer Science", hints: ["A structured set of data in rows and columns", "The basic unit of storage in relational databases", "HTML uses <___> tags to display grid data"] },
  { word: "types", category: "Computer Science", hints: ["Categories of data values", "int, string, boolean are common ___", "TypeScript adds static ___ to JavaScript"] },
  // ── Engineering & Earth Science ──
  { word: "bolts", category: "Engineering", hints: ["Threaded fasteners used with nuts", "Tightened with a wrench", "Hold structural components together"] },
  { word: "cable", category: "Engineering", hints: ["A thick rope or wire for transmitting force or signals", "Ethernet and USB are ___ types", "Suspension bridges use steel ___s"] },
  { word: "crane", category: "Engineering", hints: ["A machine for lifting heavy objects", "Uses pulleys and cables", "Common on construction sites"] },
  { word: "drain", category: "Engineering", hints: ["A channel for removing excess liquid", "Found in sinks, roads, and buildings", "Storm ___s prevent flooding"] },
  { word: "drive", category: "Engineering", hints: ["A mechanism that transmits power", "A hard ___ stores computer data", "Belt and gear ___s are common in machines"] },
  { word: "gauge", category: "Engineering", hints: ["An instrument for measuring", "Pressure and fuel ___s are common", "Also refers to wire or sheet thickness"] },
  { word: "gears", category: "Engineering", hints: ["Toothed wheels that transmit torque", "Bicycles and cars use these", "Meshing ___ change speed and direction of rotation"] },
  { word: "hinge", category: "Engineering", hints: ["A joint allowing rotation on an axis", "Doors and gates pivot on these", "Allows movement in one plane"] },
  { word: "motor", category: "Engineering", hints: ["A machine converting electrical energy to motion", "DC and AC are two main types", "Found in fans, cars, and appliances"] },
  { word: "pivot", category: "Engineering", hints: ["A fixed point around which something rotates", "The fulcrum of a lever is a ___", "A central point of rotation or decision"] },
  { word: "press", category: "Engineering", hints: ["A machine applying compressive force", "Used in manufacturing to shape materials", "A hydraulic ___ uses fluid pressure"] },
  { word: "pumps", category: "Engineering", hints: ["Devices that move fluids", "Heart is a biological one", "Centrifugal and positive-displacement are types"] },
  { word: "relay", category: "Engineering", hints: ["An electrically operated switch", "Uses a small current to control a larger one", "Common in automotive and industrial circuits"] },
  { word: "rivet", category: "Engineering", hints: ["A permanent fastener for joining metal", "Used in aircraft and bridges", "Hammered to create a head on both ends"] },
  { word: "rotor", category: "Engineering", hints: ["The rotating part of a machine", "Found in motors, turbines, and helicopters", "Opposite of the stationary stator"] },
  { word: "shaft", category: "Engineering", hints: ["A rotating rod that transmits power", "Connects a motor to its load", "Drive ___s are found in vehicles"] },
  { word: "spool", category: "Engineering", hints: ["A cylinder for winding thread or cable", "3D printers use filament on a ___", "Fishing reels contain one"] },
  { word: "strut", category: "Engineering", hints: ["A structural support resisting compression", "Used in buildings, bridges, and vehicles", "Part of a truss framework"] },
  { word: "valve", category: "Engineering", hints: ["A device controlling fluid flow", "Can be opened or closed", "The heart has four of these"] },
  { word: "welds", category: "Engineering", hints: ["Joins metal pieces using heat", "Arc and MIG are common ___ types", "Creates a permanent bond between parts"] },
  { word: "crust", category: "Earth Science", hints: ["The outermost solid layer of Earth", "Oceanic and continental are the two types", "Ranges from 5-70 km thick"] },
  { word: "epoch", category: "Earth Science", hints: ["A division of geological time", "The Holocene is the current one", "Shorter than a period, longer than an age"] },
  { word: "fault", category: "Earth Science", hints: ["A fracture in Earth's crust", "Movement along these causes earthquakes", "San Andreas is a famous one in California"] },
  { word: "plate", category: "Earth Science", hints: ["A large slab of Earth's lithosphere", "Tectonic ___s move and cause earthquakes", "There are about 15 major ones"] },
  { word: "quake", category: "Earth Science", hints: ["A sudden shaking of Earth's surface", "Measured on the Richter scale", "Caused by movement along faults"] },
  { word: "tidal", category: "Earth Science", hints: ["Relating to the rise and fall of sea levels", "Caused by gravitational pull of the Moon and Sun", "___ energy can be harnessed for power"] },
];

// Deduplicated valid words (5 lowercase alpha chars only)
export const VALID_STEM_WORDS: string[] = [
  ...new Set(
    STEM_WORD_DATA
      .map(entry => entry.word.toLowerCase())
      .filter(w => /^[a-z]{5}$/.test(w))
  )
];

// Quick lookup map: word → StemWord data (for hint retrieval)
export const WORD_MAP: Map<string, StemWord> = new Map(
  STEM_WORD_DATA
    .filter(entry => /^[a-z]{5}$/.test(entry.word.toLowerCase()))
    .map(entry => [entry.word.toLowerCase(), entry])
);

// Valid guesses — any 5-letter alpha string is accepted
export const VALID_GUESSES: Set<string> = new Set(VALID_STEM_WORDS);
